### ISSUE TITLE
Unable to run cosmos in development mode

### ISSUE THREAD

**Issue by Lakshmi5785-dev** [OpenC3/cosmos-project#15]
Hello team I am trying to run cosmos in dev mode by following the steps given in the https://docs.openc3.com/docs/development/developing link.
I didn't face any issues while running the front-end
But for the backend after running the command $bundle exec rails s I am facing the below issue
![bundle_exec_output](https://github.com/OpenC3/cosmos-project/assets/54974578/719941d0-6ce3-4af5-96a6-2303f060510b)
![treafik_dev_output](https://github.com/OpenC3/cosmos-project/assets/54974578/caaa16d5-04d2-423e-ad72-a8cc29402270)

Please help..

**Comment by Lakshmi5785-dev** [comment]
I have tried running dev_server.bat from the cosmos\openc3-cosmos-cmd-tlm-api folder. I have tried with Ruby 3.2 and Ruby 3.3 versions. But It didn't work in both the cases. Below are the results.
<img width="640" alt="Ruby3 2" src="https://github.com/OpenC3/cosmos-project/assets/54974578/2e6169d3-e75c-4b98-b04e-49659ddd370b">
<img width="778" alt="Ruby3 3" src="https://github.com/OpenC3/cosmos-project/assets/54974578/ba42c97a-e6a4-478e-a994-174a89a4db9a">
<img width="854" alt="docekr_imgs" src="https://github.com/OpenC3/cosmos-project/assets/54974578/819a7038-4993-488d-b522-f8f654f99be7">

Please help.

**Comment by ryanmelt** [comment]
You will need to comment out the works line in config/puma.rb

```
# Specifies the number of `workers` to boot in clustered mode.
# Workers are forked web server processes. If using threads and workers together
# the concurrency of the application would be max `threads` * `workers`.
# Workers do not work on JRuby or Windows (both of which do not support
# processes).
#
workers ENV.fetch("WEB_CONCURRENCY") { 4 }
```

Also why are you trying to use development mode?

**Comment by ryanmelt** [comment]
Also this is the wrong repo for this discussion.  Development mode is not supported on cosmos-project.  Closing.

**Comment by Lakshmi5785-dev** [comment]
Ohh But the Section Heading says "Developing COSMOS", Could you please help me which Project I can pick to try this.

**Comment by ryanmelt** [comment]
The regular repo: https://github.com/OpenC3/cosmos

**Comment by Lakshmi5785-dev** [comment]
Thank you for the prompt response. I am on tag V5.13.0. I will checkout to main and try.
As I am new and trying to explore OpenC3, my queries may be too basic .

**Comment by ryanmelt** [comment]
If you are new to the software you don't need to run in development mode, that is for editing our internal API code.  Just run the software with our released containers.  openc3.bat run.
