### ISSUE TITLE
Syntax error(s) in openc3.sh and openc3.bat file(s)

### ISSUE THREAD

**Issue by megIdle** [OpenC3/cosmos-project#19]
Hello! I'm trying to install from the repo on Docker, following the instructions on the OpenC3 Installation page and the ReadMe file in the repo. I'm able to clone the repo into my Alpine docker container just fine, but no matter what I do, I get the following error when trying to run <./openc3.sh run> 

ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
./openc3.sh: line 79: syntax error: unexpected "do" (expecting "fi")

I've tried adjusting the openc3.sh file directly, as well as running the openc3.bat in a windows container. 
There is also a syntax error with openc3.bat: 
./openc3.bat: line 1: @echo: not found
./openc3.bat: line 2: setlocal: not found
: not foundt: line 3:
./openc3.bat: line 4: syntax error: unexpected "(" (expecting "then").

I've tried this with OPENC3_TAG = 6.0.1 and 5.4.2. 
I confirmed in Docker Desktop and from a terminal that my container is running, and I have Docker (27.3.1), Podman (5.2.5), and Docker Compose (2.31.0) installed. 

Please advise if there's anything else I can do to resolve this. I did not see this issue anywhere else on the repo.

**Comment by ryanmelt** [comment]
This is something with your environment.
What OS are you running?

**Comment by jmthomas** [comment]
We don't support the alpine container's ash shell. You're much better off running on your native OS.

**Comment by megIdle** [comment]
That makes sense, thank you. I made that adjustment and was able to get the installation to work.


________________________________
